### PR TITLE
Add Basic Global gitignore file

### PR DESCRIPTION
**Pull request by waprin**
We can keep adding to this as more cases pop up.

### CODE REVIEW

**Comment by jeffmendoza** [comment]
IMO, things that are user specific (OSX files, editor files) should not be in repo .gitignore files. Use global .gitignore instead.

Repo .gitignore is for build artifacts, etc.

**Comment by waprin** [comment]
Hmm could see us going either way on this. Advantage of keeping user-specific stuff out:

1. Cleaner, simpler .gitignore files
2. Semantically more accurate (project is just project specific stuff)
3. Easier to maintain

Advantages of keeping it in there:

1. Not everybody realizes global gitignore exists (I did not). This way when someone clone the project, they don't even worry about those files. One .gitignore to rule them all.
2. Big ugly .gitignore files are not that big a deal.

Well known project that has user-specific stuff:
https://github.com/mitsuhiko/flask/blob/master/.gitignore
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/.gitignore

I still lean towards a big file Kubernetes style.

**Comment by jeffmendoza** [comment]
No problem to make that decision as the owner. Just something to be aware of that not all project welcome personal .gitignore additions

**Comment by waprin** [comment]
Yes I am trying to figure out what's best for GCP projects across the board. I think we should have a standard approach, these sample projects are something we collectively own.

**Comment by elibixby** [comment]
Lets keep this in ignore branch rather than master right now. That way project owners that want can still grab this file, but it won't clutter up projects by default. (Also what I did for the .travis.yml file) @jeffmendoza does that satisfy your concerns?

**Comment by jeffmendoza** [comment]
Either way is fine.

**Comment by waprin** [comment]
Thinking about it more I agree more with Jeff, I vote to just abandon.

**Comment by elibixby** [comment]
SGTM

**Pull request closed without merging**
